//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScottLogic.NumbersGame.Client.NumbersGameServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://scottlogic.co.uk", ConfigurationName="NumbersGameServiceReference.INumbersGameService")]
    public interface INumbersGameService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://scottlogic.co.uk/INumbersGameService/GetStandardGame", ReplyAction="http://scottlogic.co.uk/INumbersGameService/GetStandardGameResponse")]
        bool GetStandardGame(out int[] initialValues, out int target, int numBigValues);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://scottlogic.co.uk/INumbersGameService/GetStandardGame", ReplyAction="http://scottlogic.co.uk/INumbersGameService/GetStandardGameResponse")]
        System.IAsyncResult BeginGetStandardGame(int numBigValues, System.AsyncCallback callback, object asyncState);
        
        bool EndGetStandardGame(out int[] initialValues, out int target, System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://scottlogic.co.uk/INumbersGameService/GetAdvancedGame", ReplyAction="http://scottlogic.co.uk/INumbersGameService/GetAdvancedGameResponse")]
        bool GetAdvancedGame(out int[] initialValues, out int target, int numBigValues);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://scottlogic.co.uk/INumbersGameService/GetAdvancedGame", ReplyAction="http://scottlogic.co.uk/INumbersGameService/GetAdvancedGameResponse")]
        System.IAsyncResult BeginGetAdvancedGame(int numBigValues, System.AsyncCallback callback, object asyncState);
        
        bool EndGetAdvancedGame(out int[] initialValues, out int target, System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INumbersGameServiceChannel : ScottLogic.NumbersGame.Client.NumbersGameServiceReference.INumbersGameService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetStandardGameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetStandardGameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int[] initialValues {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int[])(this.results[0]));
            }
        }
        
        public int target {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[2]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAdvancedGameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAdvancedGameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int[] initialValues {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int[])(this.results[0]));
            }
        }
        
        public int target {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[2]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NumbersGameServiceClient : System.ServiceModel.ClientBase<ScottLogic.NumbersGame.Client.NumbersGameServiceReference.INumbersGameService>, ScottLogic.NumbersGame.Client.NumbersGameServiceReference.INumbersGameService {
        
        private BeginOperationDelegate onBeginGetStandardGameDelegate;
        
        private EndOperationDelegate onEndGetStandardGameDelegate;
        
        private System.Threading.SendOrPostCallback onGetStandardGameCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAdvancedGameDelegate;
        
        private EndOperationDelegate onEndGetAdvancedGameDelegate;
        
        private System.Threading.SendOrPostCallback onGetAdvancedGameCompletedDelegate;
        
        public NumbersGameServiceClient() {
        }
        
        public NumbersGameServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NumbersGameServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NumbersGameServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NumbersGameServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetStandardGameCompletedEventArgs> GetStandardGameCompleted;
        
        public event System.EventHandler<GetAdvancedGameCompletedEventArgs> GetAdvancedGameCompleted;
        
        public bool GetStandardGame(out int[] initialValues, out int target, int numBigValues) {
            return base.Channel.GetStandardGame(out initialValues, out target, numBigValues);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetStandardGame(int numBigValues, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetStandardGame(numBigValues, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndGetStandardGame(out int[] initialValues, out int target, System.IAsyncResult result) {
            return base.Channel.EndGetStandardGame(out initialValues, out target, result);
        }
        
        private System.IAsyncResult OnBeginGetStandardGame(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int numBigValues = ((int)(inValues[0]));
            return this.BeginGetStandardGame(numBigValues, callback, asyncState);
        }
        
        private object[] OnEndGetStandardGame(System.IAsyncResult result) {
            int[] initialValues = this.GetDefaultValueForInitialization<int[]>();
            int target = this.GetDefaultValueForInitialization<int>();
            bool retVal = this.EndGetStandardGame(out initialValues, out target, result);
            return new object[] {
                    initialValues,
                    target,
                    retVal};
        }
        
        private void OnGetStandardGameCompleted(object state) {
            if ((this.GetStandardGameCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetStandardGameCompleted(this, new GetStandardGameCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetStandardGameAsync(int numBigValues) {
            this.GetStandardGameAsync(numBigValues, null);
        }
        
        public void GetStandardGameAsync(int numBigValues, object userState) {
            if ((this.onBeginGetStandardGameDelegate == null)) {
                this.onBeginGetStandardGameDelegate = new BeginOperationDelegate(this.OnBeginGetStandardGame);
            }
            if ((this.onEndGetStandardGameDelegate == null)) {
                this.onEndGetStandardGameDelegate = new EndOperationDelegate(this.OnEndGetStandardGame);
            }
            if ((this.onGetStandardGameCompletedDelegate == null)) {
                this.onGetStandardGameCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetStandardGameCompleted);
            }
            base.InvokeAsync(this.onBeginGetStandardGameDelegate, new object[] {
                        numBigValues}, this.onEndGetStandardGameDelegate, this.onGetStandardGameCompletedDelegate, userState);
        }
        
        public bool GetAdvancedGame(out int[] initialValues, out int target, int numBigValues) {
            return base.Channel.GetAdvancedGame(out initialValues, out target, numBigValues);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetAdvancedGame(int numBigValues, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAdvancedGame(numBigValues, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndGetAdvancedGame(out int[] initialValues, out int target, System.IAsyncResult result) {
            return base.Channel.EndGetAdvancedGame(out initialValues, out target, result);
        }
        
        private System.IAsyncResult OnBeginGetAdvancedGame(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int numBigValues = ((int)(inValues[0]));
            return this.BeginGetAdvancedGame(numBigValues, callback, asyncState);
        }
        
        private object[] OnEndGetAdvancedGame(System.IAsyncResult result) {
            int[] initialValues = this.GetDefaultValueForInitialization<int[]>();
            int target = this.GetDefaultValueForInitialization<int>();
            bool retVal = this.EndGetAdvancedGame(out initialValues, out target, result);
            return new object[] {
                    initialValues,
                    target,
                    retVal};
        }
        
        private void OnGetAdvancedGameCompleted(object state) {
            if ((this.GetAdvancedGameCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAdvancedGameCompleted(this, new GetAdvancedGameCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAdvancedGameAsync(int numBigValues) {
            this.GetAdvancedGameAsync(numBigValues, null);
        }
        
        public void GetAdvancedGameAsync(int numBigValues, object userState) {
            if ((this.onBeginGetAdvancedGameDelegate == null)) {
                this.onBeginGetAdvancedGameDelegate = new BeginOperationDelegate(this.OnBeginGetAdvancedGame);
            }
            if ((this.onEndGetAdvancedGameDelegate == null)) {
                this.onEndGetAdvancedGameDelegate = new EndOperationDelegate(this.OnEndGetAdvancedGame);
            }
            if ((this.onGetAdvancedGameCompletedDelegate == null)) {
                this.onGetAdvancedGameCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAdvancedGameCompleted);
            }
            base.InvokeAsync(this.onBeginGetAdvancedGameDelegate, new object[] {
                        numBigValues}, this.onEndGetAdvancedGameDelegate, this.onGetAdvancedGameCompletedDelegate, userState);
        }
    }
}
